name: Deploy to railway

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
              push: true
              tags: camilodevp/server-bot-telegram:latest

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to railway
        run: railway up --service gentle-finger
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
